version: "3.8"

services:
  app:
    container_name: my-app-prod
    image: your-docker-username/my-node-app:latest
    ports:
      - "9191:9191"
    environment:
      - PORT=9191
      - MONGO_URI=mongodb://mongo:27017/tasks
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
