version: "3.8"

services:
  app:
    container_name: my-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9191:9191"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=9191
      - MONGO_URI=mongodb://mongo:27017/tasks
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
